version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && psql --username=postgres --list" ]
      timeout: 10s
      retries: 20


